network/api/urls.py
from rest_framework import routers
from network.api import views


router = routers.DefaultRouter()

router.register(r'jobs', views.JobView, base_name='jobs')
router.register(r'data', views.ObservationView, base_name='data')
router.register(r'observations', views.ObservationView, base_name='observations')
router.register(r'settings', views.SettingsView, base_name='settings')
router.register(r'stations', views.StationView, base_name='stations')

api_urlpatterns = router.urls

network/base/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from network.base import views

base_urlpatterns = ([
    url(r'^$', views.index, name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='base/about.html'), name='about'),
    url(r'^robots\.txt$', views.robots, name='robots'),
    url(r'^settings_site/$', views.settings_site, name='settings_site'),

    # Observations
    url(r'^observations/$', views.ObservationListView.as_view(), name='observations_list'),
    url(r'^observations/(?P<id>[0-9]+)/$', views.observation_view,
        name='observation_view'),
    url(r'^observations/(?P<id>[0-9]+)/delete/$', views.observation_delete,
        name='observation_delete'),
    url(r'^observations/new/$', views.observation_new, name='observation_new'),
    url(r'^prediction_windows/(?P<sat_id>[\w.@+-]+)/(?P<transmitter>[\w.@+-]+)/'
        '(?P<start_date>.+)/(?P<end_date>.+)/(?P<station_id>[\w.@+-]+)/$',
        views.prediction_windows, name='prediction_windows_filtered'),
    url(r'^prediction_windows/(?P<sat_id>[\w.@+-]+)/(?P<transmitter>[\w.@+-]+)/'
        '(?P<start_date>.+)/(?P<end_date>.+)/$',
        views.prediction_windows, name='prediction_windows'),
    url(r'^pass_predictions/(?P<id>[\w.@+-]+)/$',
        views.pass_predictions, name='pass_predictions'),
    url(r'^observation_vet/(?P<id>[0-9]+)/(?P<status>[a-z]+)/$', views.observation_vet,
        name='observation_vet'),

    # Stations
    url(r'^stations/$', views.stations_list, name='stations_list'),
    url(r'^stations/(?P<id>[0-9]+)/$', views.station_view, name='station_view'),
    url(r'^stations/(?P<id>[0-9]+)/log/$', views.station_log, name='station_log'),
    url(r'^stations/(?P<id>[0-9]+)/delete/$', views.station_delete, name='station_delete'),
    url(r'^stations/edit/$', views.station_edit, name='station_edit'),
    url(r'^stations/edit/(?P<id>[0-9]+)/$', views.station_edit, name='station_edit'),
    url(r'^stations_all/$', views.StationAllView.as_view({'get': 'list'}), name='stations_all'),

    # Satellites
    url(r'^satellites/(?P<id>[0-9]+)/$', views.satellite_view, name='satellite_view'),
    url(r'^satellite_position/(?P<sat_id>[0-9]+)/$', views.satellite_position,
        name='satellite_position'),
], 'base')

network/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.static import serve

from avatar import urls as avatar_urls
from allauth import urls as allauth_urls

from network.base.urls import base_urlpatterns
from network.users.urls import users_urlpatterns
from network.api.urls import api_urlpatterns

handler404 = 'network.base.views.custom_404'
handler500 = 'network.base.views.custom_500'

urlpatterns = [
    # Base urls
    url(r'^', include(base_urlpatterns)),

    url(r'^admin/', admin.site.urls),
    url(r'^users/', include(users_urlpatterns)),
    url(r'^accounts/', include(allauth_urls)),
    url(r'^avatar/', include(avatar_urls)),

    url(r'^api/', include(api_urlpatterns))
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT}),
    ]

network/users/urls.py
from django.conf.urls import url

from network.users import views

users_urlpatterns = ([
    url(r'^redirect/$', views.UserRedirectView.as_view(), name='redirect_user'),
    url(r'^update/$', views.UserUpdateView.as_view(), name='update_user'),
    url(r'^(?P<username>[\w.@+-]+)/$', views.view_user, name='view_user'),
], 'users')

network/base/models.py
import os
from datetime import datetime, timedelta
from PIL import Image
import requests
from shortuuidfield import ShortUUIDField

from django.conf import settings
from django.core.cache import cache
from django.core.validators import MaxValueValidator, MinValueValidator
from django.dispatch import receiver
from django.db import models
from django.db.models.signals import post_save
from django.urls import reverse
from django.utils.html import format_html
from django.utils.timezone import now

from network.users.models import User
from network.base.helpers import get_apikey
from network.base.managers import ObservationManager


RIG_TYPES = ['Radio', 'SDR']
ANTENNA_BANDS = ['HF', 'VHF', 'UHF', 'L', 'S', 'C', 'X', 'KU']
ANTENNA_TYPES = (
    ('dipole', 'Dipole'),
    ('yagi', 'Yagi'),
    ('helical', 'Helical'),
    ('parabolic', 'Parabolic'),
    ('vertical', 'Verical'),
    ('turnstile', 'Turnstile'),
    ('quadrafilar', 'Quadrafilar'),
    ('eggbeater', 'Eggbeater'),
    ('lindenblad', 'Lindenblad'),
    ('paralindy', 'Parasitic Lindenblad')
)
OBSERVATION_STATUSES = (
    ('unknown', 'Unknown'),
    ('good', 'Good'),
    ('bad', 'Bad'),
    ('failed', 'Failed'),
)
STATION_STATUSES = (
    (2, 'Online'),
    (1, 'Testing'),
    (0, 'Offline'),
)
SATELLITE_STATUS = ['alive', 'dead', 're-entered']


def _name_obs_files(instance, filename):
    return 'data_obs/{0}/{1}'.format(instance.id, filename)


def _name_obs_demoddata(instance, filename):
    return 'data_obs/{0}/{1}'.format(instance.observation.id, filename)


def _observation_post_save(sender, instance, created, **kwargs):
    """
    Post save Observation operations
    * Auto vet as good obserfvation with Demod Data
    * Mark Observations from testing stations
    """
    post_save.disconnect(_observation_post_save, sender=Observation)
    if created and instance.ground_station.testing:
        instance.testing = True
        instance.save()
    if instance.has_demoddata:
        instance.vetted_status = 'good'
        instance.vetted_datetime = now()
        instance.save()
    post_save.connect(_observation_post_save, sender=Observation)


def _station_post_save(sender, instance, created, **kwargs):
    """
    Post save Station operations
    * Store current status
    """
    post_save.disconnect(_station_post_save, sender=Station)
    if not created:
        current_status = instance.status
        if instance.is_offline:
            instance.status = 0
        elif instance.testing:
            instance.status = 1
        else:
            instance.status = 2
        instance.save()
        if instance.status != current_status:
            StationStatusLog.objects.create(station=instance, status=instance.status)
    else:
        StationStatusLog.objects.create(station=instance, status=instance.status)
    post_save.connect(_station_post_save, sender=Station)


class Rig(models.Model):
    """Model for Rig types."""
    name = models.CharField(choices=zip(RIG_TYPES, RIG_TYPES), max_length=10)
    rictld_number = models.PositiveIntegerField(blank=True, null=True)

    def __unicode__(self):
        return '{0}: {1}'.format(self.name, self.rictld_number)


class Mode(models.Model):
    """Model for Modes."""
    name = models.CharField(max_length=10, unique=True)

    def __unicode__(self):
        return self.name


class Antenna(models.Model):
    """Model for antennas tracked with SatNOGS."""
    frequency = models.PositiveIntegerField()
    frequency_max = models.PositiveIntegerField()
    band = models.CharField(choices=zip(ANTENNA_BANDS, ANTENNA_BANDS),
                            max_length=5)
    antenna_type = models.CharField(choices=ANTENNA_TYPES, max_length=15)

    def __unicode__(self):
        return '{0} - {1} - {2} - {3}'.format(self.band, self.antenna_type,
                                              self.frequency,
                                              self.frequency_max)


class Station(models.Model):
    """Model for SatNOGS ground stations."""
    owner = models.ForeignKey(User, related_name="ground_stations",
                              on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=45)
    image = models.ImageField(upload_to='ground_stations', blank=True)
    alt = models.PositiveIntegerField(help_text='In meters above ground')
    lat = models.FloatField(validators=[MaxValueValidator(90), MinValueValidator(-90)],
                            help_text='eg. 38.01697')
    lng = models.FloatField(validators=[MaxValueValidator(180), MinValueValidator(-180)],
                            help_text='eg. 23.7314')
    qthlocator = models.CharField(max_length=255, blank=True)
    location = models.CharField(max_length=255, blank=True)
    antenna = models.ManyToManyField(Antenna, blank=True,
                                     help_text=('If you want to add a new Antenna contact '
                                                '<a href="https://community.satnogs.org/" '
                                                'target="_blank">SatNOGS Team</a>'))
    featured_date = models.DateField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    testing = models.BooleanField(default=True)
    last_seen = models.DateTimeField(null=True, blank=True)
    status = models.IntegerField(choices=STATION_STATUSES, default=0)
    horizon = models.PositiveIntegerField(help_text='In degrees above 0', default=10)
    uuid = models.CharField(db_index=True, max_length=100, blank=True)
    rig = models.ForeignKey(Rig, related_name='ground_stations',
                            on_delete=models.SET_NULL, null=True, blank=True)
    description = models.TextField(max_length=500, blank=True, help_text='Max 500 characters')

    class Meta:
        ordering = ['-status']

    def get_image(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
        else:
            return settings.STATION_DEFAULT_IMAGE

    @property
    def is_online(self):
        try:
            heartbeat = self.last_seen + timedelta(minutes=int(settings.STATION_HEARTBEAT_TIME))
            return heartbeat > now()
        except TypeError:
            return False

    @property
    def is_offline(self):
        return not self.is_online

    @property
    def is_testing(self):
        if self.is_online:
            if self.status == 1:
                return True
        return False

    def state(self):
        if not self.status:
            return format_html('<span style="color:red;">Offline</span>')
        if self.status == 1:
            return format_html('<span style="color:orange;">Testing</span>')
        return format_html('<span style="color:green">Online</span>')

    @property
    def success_rate(self):
        rate = cache.get('sat-{0}-rate'.format(self.id))
        if not rate:
            observations = self.observations.exclude(testing=True)
            has_audio = observations.filter(id__in=(o.id for o in observations if o.has_audio))
            success = has_audio.count()
            if observations:
                rate = int(100 * (float(success) / float(observations.count())))
                cache.set('sat-{0}-rate'.format(self.id), rate)
            else:
                rate = False
        return rate

    @property
    def observations_count(self):
        count = self.observations.all().count()
        return count

    @property
    def observations_future_count(self):
        count = self.observations.is_future().count()
        return count

    @property
    def apikey(self):
        return get_apikey(user=self.owner)

    def __unicode__(self):
        return "%d - %s" % (self.pk, self.name)


post_save.connect(_station_post_save, sender=Station)


class StationStatusLog(models.Model):
    station = models.ForeignKey(Station, related_name='station_logs',
                                on_delete=models.CASCADE, null=True, blank=True)
    status = models.IntegerField(choices=STATION_STATUSES, default=0)
    changed = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-changed']

    def __unicode__(self):
        return '{0} - {1}'.format(self.station, self.status)


class Satellite(models.Model):
    """Model for SatNOGS satellites."""
    norad_cat_id = models.PositiveIntegerField()
    name = models.CharField(max_length=45)
    names = models.TextField(blank=True)
    image = models.CharField(max_length=100, blank=True, null=True)
    manual_tle = models.BooleanField(default=False)
    status = models.CharField(choices=zip(SATELLITE_STATUS, SATELLITE_STATUS),
                              max_length=10, default='alive')

    class Meta:
        ordering = ['norad_cat_id']

    def get_image(self):
        if self.image:
            return self.image
        else:
            return settings.SATELLITE_DEFAULT_IMAGE

    @property
    def latest_tle(self):
        try:
            latest_tle = Tle.objects.filter(satellite=self).latest('updated')
            return latest_tle
        except Tle.DoesNotExist:
            return False

    @property
    def tle_no(self):
        try:
            line = self.latest_tle.tle1
            return line[65:68]
        except AttributeError:
            return False

    @property
    def tle_epoch(self):
        try:
            line = self.latest_tle.tle1
        except AttributeError:
            return False
        yd, s = line[18:32].split('.')
        epoch = (datetime.strptime(yd, "%y%j") +
                 timedelta(seconds=float("." + s) * 24 * 60 * 60))
        return epoch

    @property
    def data_count(self):
        return Observation.objects.filter(satellite=self).count()

    @property
    def good_count(self):
        data = Observation.objects.filter(satellite=self)
        return data.filter(vetted_status='good').count()

    @property
    def bad_count(self):
        data = Observation.objects.filter(satellite=self)

network/base/forms.py
from django import forms

from network.base.models import Station


class StationForm(forms.ModelForm):
    class Meta:
        model = Station
        fields = ['name', 'image', 'alt', 'rig', 'lat', 'lng', 'qthlocator',
                  'horizon', 'antenna', 'testing', 'description']
        image = forms.ImageField(required=False)


class SatelliteFilterForm(forms.Form):
    norad = forms.IntegerField()
    start_date = forms.CharField(required=False)
    end_date = forms.CharField(required=False)
    ground_station = forms.IntegerField(required=False)

network/users/forms.py
from django import forms

from network.users.models import User


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ("first_name", "last_name")

network/api/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.utils.timezone import now

from rest_framework import viewsets, mixins, status
from rest_framework.response import Response

from network.api.perms import StationOwnerCanEditPermission
from network.api import serializers, filters, pagination
from network.base.models import Observation, Station


class ObservationView(viewsets.ModelViewSet, mixins.UpdateModelMixin):
    queryset = Observation.objects.all()
    serializer_class = serializers.ObservationSerializer
    filter_class = filters.ObservationViewFilter
    permission_classes = [
        StationOwnerCanEditPermission
    ]
    pagination_class = pagination.LinkedHeaderPageNumberPagination

    def update(self, request, *args, **kwargs):
        if request.data.get('demoddata'):
            instance = self.get_object()
            instance.demoddata.create(payload_demod=request.data.get('demoddata'))

        super(ObservationView, self).update(request, *args, **kwargs)
        return Response(status=status.HTTP_200_OK)


class StationView(viewsets.ModelViewSet, mixins.UpdateModelMixin):
    queryset = Station.objects.all()
    serializer_class = serializers.StationSerializer
    pagination_class = pagination.LinkedHeaderPageNumberPagination


class JobView(viewsets.ReadOnlyModelViewSet):
    queryset = Observation.objects.filter(payload='')
    serializer_class = serializers.JobSerializer
    filter_class = filters.ObservationViewFilter
    filter_fields = ('ground_station')

    def get_queryset(self):
        queryset = self.queryset.filter(start__gte=now())
        gs_id = self.request.query_params.get('ground_station', None)
        if gs_id and self.request.user.is_authenticated():
            gs = get_object_or_404(Station, id=gs_id)
            if gs.owner == self.request.user:
                gs.last_seen = now()
                gs.save()
        return queryset


class SettingsView(viewsets.ReadOnlyModelViewSet):
    queryset = Station.objects.all()
    lookup_field = 'uuid'

    def list(self, request):
        raise Http404()

    def retrieve(self, request, queryset=queryset, uuid=None):
        station = get_object_or_404(queryset, uuid=uuid)
        serializer = serializers.SettingsSerializer(station)
        return Response(serializer.data)

network/templates/users/user_detail.html
{% extends "base.html" %}
{% load avatar_tags %}
{% load static %}
{% load tags %}

{% block title %}
  {% if user == request.user %} - Dashboard{% else %} - User: {{ user.username }}{% endif %}
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-sm-12">
      <h2>{% avatar user 50 %} {{ user.displayname }}
        {% if user == request.user %}
          <div class="pull-right edit-profile-buttons">
            <a class="btn btn-primary" href="{% url 'users:update_user' %}">Settings</a>
            <a class="btn btn-primary" href="{% url 'account_email' %}">Email</a>
            <a class="btn btn-primary" href="{% url 'avatar_change' %}">Avatar</a>
            <a class="btn btn-info" data-toggle="modal" data-target="#APIModal" href="#">API Key</a>
          </div>
        {% endif %}
      </h2>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <h3>Ground Stations</h3>
    </div>
  </div>

  {% if stations %}
    <div class="row">
      <div class="col-md-12">
        <table class="table table-hover">
          <thead>
            <th>ID</th>
            <th>Name</th>
            <th>Location</th>
            <th>Total</th>
            <th>Future</th>
            <th>Antennas</th>
          </thead>
          <tbody>
            {% for station in stations.all %}
              <tr class="clickable-row" data-href="{% url 'base:station_view' id=station.id %}">
                <td>
                  <a href="{% url 'base:station_view' id=station.id %}">
                    <span class="label label-{{ station.get_status_display|lower }}"
                          data-toggle="tooltip"
                          data-placement="bottom"
                          title="{% if station.last_seen %}
                                   Seen {{ station.last_seen|timesince }} ago
                                 {% else %}
                                   label-danger
                                 {% endif %}"
                          data-toggle="tooltip"
                          data-placement="bottom"
                          title="{% if station.last_seen %}
                                   Seen {{ station.last_seen|timesince }} ago
                                 {% else %}
                                   Never seen
                                 {% endif %}">
                      {{ station.id }}
                    </span>
                  </a>
                </td>
                <td>
                  {{ station.name }}
                </td>
                {% if station.location %}
                  <td title="{{ station.lat|floatformat:-3 }}°, {{ station.lng|floatformat:-3 }}°, {{ station.qthlocator }}">
                    {{ station.location }}
                  </td>
                {% else %}
                  <td>
                    {% if station.qthlocator %}
                      <span data-toggle="tooltip" data-placement="bottom"
                            title="{{ station.lat|floatformat:-3 }}°, {{ station.lng|floatformat:-3 }}°">
                      {{ station.qthlocator }}
                    {% else %}
                      {{ station.lat|floatformat:-1 }}°, {{ station.lng|floatformat:-1 }}°
                    {% endif %}
                    @{{ station.alt}}m
                  </td>
                {% endif %}
                <td>
                  <a href="{% url 'base:observations_list' %}?station={{ station.id }}">
                    <span class="badge total-pill" data-toggle="tooltip" data-placement="bottom"
                          title="{{ station.success_rate }}% Success">
                      {{ station.observations_count }}
                    </span>
                  </a>
                </td>
                <td>
                  <a href="{% url 'base:observations_list' %}?future=1&good=0&bad=0&unvetted=0&failed=0&station={{ station.id }}">
                    <span class="badge badge-info">
                      {{ station.observations_future_count }}
                    </span>
                  </a>
                </td>
                <td class="station-antennas">
                  {% for antenna in station.antenna.all %}
                    <span class="antenna-pill" data-toggle="tooltip" data-placement="bottom"
                          title="{{ antenna.frequency|frq }} - {{ antenna.frequency_max|frq }}">
                      {{ antenna.band}} {{ antenna.get_antenna_type_display }}
                    </span>
                  {% endfor %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  {% else %}
    <div class="row">
      <div class="col-md-12 notice">
        <p>{{ user.displayname }} is not an owner of any ground stations.</p>
      </div>
    </div>
  {% endif %}

  {% if user == request.user %}
    <div class="row">
      <div class="col-md-12">
        <a class="btn btn-default" href="{% url 'base:station_edit' %}">
          <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add Ground Station
        </a>
      </div>
    </div>
  {% endif %}

  <div class="row">
    <div class="col-md-12">
      <h3>Observations</h3>
    </div>
  </div>

  {% if observations %}
    <div class="row">
      <div class="col-md-12">
        <table class="table table-hover">
          <thead>
            <th>ID</th>
            <th>Satellite</th>
            <th>Frequency</th>
            <th>Encoding</th>
            <th>Timeframe</th>
            <th>Station</th>
          </thead>
          <tbody>
            {% for observation in observations.all %}
              <tr class="clickable-row" data-href="{% url 'base:observation_view' id=observation.id %}">
                <td>
                  <a href="{% url 'base:observation_view' id=observation.id %}">
                    {% if observation.is_vetted %}
                      <span class="label label-{{observation.vetted_status }}">{{ observation.id }}</span>
                    {% elif observation.is_future %}
                      <span class="label label-future">{{ observation.id }}</span>
                    {% else %}
                      <span class="label label-unknown">{{ observation.id }}</span>
                    {% endif %}
                  </a>
                </td>
                <td>
                  <a href="#" data-toggle="modal" data-target="#SatelliteModal" data-id="{{ observation.satellite.norad_cat_id }}">
                    {{ observation.satellite.name }}
                  </a>
                </td>
                <td>{{ observation.transmitter.downlink_low|frq }}</td>
                <td>{{ observation.transmitter.mode }}</td>
                <td>
                  <span class="datetime-date">{{ observation.start|date:"Y-m-d" }}</span>
                  <span class="datetime-time">{{ observation.start|date:"H:i:s" }}</span><br>
                  <span class="datetime-date">{{ observation.end|date:"Y-m-d" }}</span>
                  <span class="datetime-time">{{ observation.end|date:"H:i:s" }}</span>
                </td>
                <td>
                  {% if observation.ground_station %}
                    <a href="{% url 'base:station_view' id=observation.ground_station.id %}">
                      {{ observation.ground_station }}
                    </a>
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  {% else %}
    <div class="row">
      <div class="col-md-12 notice">
        <p>{{ user.displayname }} is not an author of any observation.</p>
      </div>
    </div>
  {% endif %}

  {% if can_schedule %}
    <div class="row">
      <div class="col-md-12">
        <a class="btn btn-default" href="{% url 'base:observation_new' %}">
          <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
          New Observation
        </a>
      </div>
    </div>
  {% endif %}

  <!-- API Modal -->
  <div class="modal fade" id="APIModal" tabindex="-1" role="dialog" aria-labelledby="APIModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="APIModalLabel">API Key</h4>
        </div>
        <div class="modal-body">
          <div>You can use this token to interact with the API.</div>
          <div>
            <code>{{ token }}</code>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

  {% include 'includes/satellite.html' %}
{% endblock content %}

{% block javascript %}
  <script src="{% static 'js/satellite.js' %}"></script>
{% endblock javascript %}

network/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load avatar_tags %}

{% block title %} - Settings{% endblock %}

{% block content %}
  <h2>{% block header %}User: {{ user.username }}{% endblock %}</h2>

  <div class="row">
    <div class="col-md-5">
      <form method="post"
            action="{% url 'users:update_user' %}">{% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
          <div class="controls">
            <button type="submit" class="btn btn-sm btn-primary">Update</button>
          </div>
        </div>
      </form>
    </div>
    <div class="col-md-10">
      <a href="{% url 'account_change_password' %}">
        Click here to change your password
      </a>
    </div>
  </div>
{% endblock %}